### ISSUE TITLE
how to add condition in template?

### ISSUE THREAD

**Issue by bogdandragomir** [jorix/OL-FeaturePopups#8]
Hi!

I need to add a condition like this:

```
item:   function(feature) {
   return '<li><a href=\"#\" ${showPopup()}>' + feature.attributes.name + '</a>' +
      (feature.attributes.available == "0" ? " (unavailable)" : "") + '</li>';
},
```

In this example the "${showPopup()}" template does not work.

But if I use 

```
item:   '<li><a href=\"#\" ${showPopup()}>' + feature.attributes.name + '</a>' +
      (feature.attributes.available == "0" ? " (unavailable)" : "") + '</li>',
```

_feature_ object does not exists.

Which is the correct syntax?
Thank you!

**Comment by jorix** [comment]
@bogdandragomir 

I'm working on this... new FEATURE: `overlaidContexts` 

When I finished (a couple of days) you could write code like this:

```
templates: {
  item:   '<li><a href=\"#\" ${showPopup()}>${.name}</a>${isUnavailable}</li>',
  ...
},
overlaidContexts: {
  feature: {
    isUnavailable: function(feature) {
      return feature.attributes.available == "0" ? " (unavailable)" : "";
    }
  }
},
...
```

**Comment by bogdandragomir** [comment]
Thank you Jorix. 
I am a little surprised, there is no simple solution for this problem, but a new feature?

**Comment by jorix** [comment]
Don't worry, the hardest part is to extend the OpenLayers.String.format utility and test.

Later I also prepared a way for the templates as a functions.

(thought it was a weakness that should be provided)

Regards,

Xavier

---

De: Bogdan [mailto:notifications@github.com] 
Enviado el: martes, 18 de diciembre de 2012 21:22
Para: jorix/OL-FeaturePopups
CC: Xavier Mamano
Asunto: Re: [OL-FeaturePopups] how to add condition in template? (#8)

Thank you Jorix. 
I am a little surprised, there is no simple solution for this problem, but a
new feature?

## 

Reply to this email directly or view
https://github.com/jorix/OL-FeaturePopups/issues/8#issuecomment-11503384
it on GitHub. 

<https://github.com/notifications/beacon/AbWkxnmM90IPlQrEr6FQKy2lO28Rg4u29Ui
9WTHfEs2XWfeAPPvZtodutAK_ZCgi.gif>

**Comment by jorix** [comment]
Yes, is curious. Try add coment by GitHub, not as email.

---

De: Bogdan [mailto:notifications@github.com] 
Enviado el: martes, 18 de diciembre de 2012 21:25
Para: jorix/OL-FeaturePopups
CC: Xavier Mamano
Asunto: Re: [OL-FeaturePopups] how to add condition in template? (#8)

It looks like I still can not add new comments.
I don't know what could it be, I tried with two browsers.
Is it necessary to buy an account on github?

Thank you,
Bogdan 

## 

Reply to this email directly or view
https://github.com/jorix/OL-FeaturePopups/issues/8#issuecomment-11503471
it on GitHub. 

<https://github.com/notifications/beacon/AbWkxnmM90IPlQrEr6FQKy2lO28Rg4u29Ui
9WTHfEs2XWfeAPPvZtodutAK_ZCgi.gif>

**Comment by jorix** [comment]
Hi Bogdan,

I've never used, but in your situation I would try help on
https://help.github.com/contact

I have observed that all your comments are gone, but the other user comments
remain :((

Good luck with the GitHub support!

Xavier

---

De: Bogdan [mailto:notifications@github.com] 
Enviado el: martes, 18 de diciembre de 2012 22:21
Para: jorix/OL-FeaturePopups
CC: Xavier Mamano
Asunto: Re: [OL-FeaturePopups] how to add condition in template? (#8)

I tried, before trying by email.

Pe 18.12.2012 23:17, Xavier Mamano a scris:

> Yes, is curious. Try add coment by GitHub, not as email.
> 
> ---
> 
> De: Bogdan [mailto:notifications@github.com]
> Enviado el: martes, 18 de diciembre de 2012 21:25
> Para: jorix/OL-FeaturePopups
> CC: Xavier Mamano
> Asunto: Re: [OL-FeaturePopups] how to add condition in template? (#8)
> 
> It looks like I still can not add new comments.
> I don't know what could it be, I tried with two browsers.
> Is it necessary to buy an account on github?
> 
> Thank you,
> Bogdan
> 
> ## 
> 
> Reply to this email directly or view
> https://github.com/jorix/OL-FeaturePopups/issues/8#issuecomment-11503471
> it on GitHub.
> 
> <https://github.com/notifications/beacon/AbWkxnmM90IPlQrEr6FQKy2lO28Rg4u29Ui
> 9WTHfEs2XWfeAPPvZtodutAK_ZCgi.gif>
> 
> ## 
> 
> Reply to this email directly or view it on GitHub 
> 
> https://github.com/jorix/OL-FeaturePopups/issues/8#issuecomment-11505554. 

## 

Reply to this email directly or view
https://github.com/jorix/OL-FeaturePopups/issues/8#issuecomment-11505661
it on GitHub. 

<https://github.com/notifications/beacon/AbWkxnmM90IPlQrEr6FQKy2lO28Rg4u29Ui
9WTHfEs2XWfeAPPvZtodutAK_ZCgi.gif>

**Comment by jorix** [comment]
@bogdandragomir  I contacted GitHub support, and it's fixed :-)

...they say: _"we introduced some new measures to fight spam, and that user's account was incorrectly flagged as spammy"_

**Comment by bogdandragomir** [comment]
Thank you very much Jorix!

**Comment by jorix** [comment]
@bogdandragomir 

I think I solved two weaknesses: the conditions on the templates and use of "fid" 816b1ece43f2f2f3d4e9d96f43b1d0f175f382c1 + 3292db369fb238991eb917aba409df73c5eca182

Now you could use:

```
templates: {
  item:   '<li><a href=\"#\" ${showPopup()}>${.name}</a>${isUnavailable}</li>',
  ...
},
featureContext: {
    isUnavailable: function(feature) {
      return feature.attributes.available == "0" ? " (unavailable)" : "";
   },
   fid: function(feature) {
      return feature.id; // see comment below!
   }
},
```

why declare the fid? "fid" of the features in "trafficguide" are not unique and this causes problems using `FeaturePupups` + `SAFE_SELECTION`: after zooming, all features with the same fid appear selected if one of them is selected.

But it may be that this is also valid:

```
fid: function(feature) {
      return feature.attributes.tip + feature.fid;
}
```

and allow also work with the `BBOX` strategy.

**Comment by jorix** [comment]
@bogdandragomir  Yesterday I forgot an **important** detail!

When filtering features, as in your case, you should use a simpler function `applyTemplate` instead of `renderTemplate`, see the changes in the example ca9f7a3844d7160af9f3f73378a9cb6d695c3f3f

**Comment by bogdandragomir** [comment]
Hi!

I updated the FeaturePopups.js and patches_OL-popup-autosize.js files on test server and added the featureContext lines. I have this error now when I click on a cluster icon.

TypeError: _extendedContext is undefined
replacement = _extendedContext['undefined'];
FeaturePopups.js (line 1875)

See it here: http://test2.trafficguide.ro/

You have a small typo in this line:
return feature.attribute.tip + feature.fid;
It is missing a S: feature.attributes.tip.

Thank you!

**Comment by jorix** [comment]
@bogdandragomir 

> TypeError: _extendedContext is undefined

I think it is fixed by [this diff](https://github.com/jorix/OL-FeaturePopups/commit/4199ca98a0574c5e800767172fdbf072036bb8a2#L0R2096), thanks.

Now could also use

```
...
hover: "${.name}${eIndisponibila}",
hoverItem: "${.name}${eIndisponibila}<br>",
...
```

> You have a small typo in this line:

ok

**Comment by bogdandragomir** [comment]
> I think it is fixed by this diff, thanks.

I have updated the FeaturePopups.js file but the popup on cluster icon click still not appear.
http://test2.trafficguide.ro/

> Now could also use

You are right. But it looks like you add some more spaces between these structures: ${.name}${eIndisponibila}.
Please look at this screenshot:
![snap178](https://f.cloud.github.com/assets/2846921/29817/0150cf02-4dce-11e2-9256-b9471a8c1cae.jpg)

Thank you!

**Comment by bogdandragomir** [comment]
> I have updated the FeaturePopups.js file but the popup on cluster icon click still not appear

I think I found. I need to add these lines for each layer on my map:

```
            featureContext: {
                fid: function(feature) {
                    return feature.attributes.tip + feature.fid;
                }
            }
```

Is this true?

**Comment by bogdandragomir** [comment]
I have a new problem and I think it is related to the recent changes because on the production server it doesn't happen.

Please look at this screenshot:
![snap179](https://f.cloud.github.com/assets/2846921/29822/0b8807b8-4dd0-11e2-8ce5-4284d9e93563.jpg)

The 2nd popup (click on first feature of the cluster popup) is anchored in a strange position.
And when zoom in the situation is more strange:
![snap180](https://f.cloud.github.com/assets/2846921/29823/892224f6-4dd0-11e2-83bb-271a92f29baf.jpg)

Maybe this is the explanation:
we have situations described by 2 points on map, ussualy at the ends of the road with problems (marked with black on the map).
And maybe they have the same created fid ({tip} + {id}).

Can you imagine a solution for this?

Thank you!

**Comment by jorix** [comment]
> I have updated the FeaturePopups.js file but the popup on cluster icon click still not appear.

now I've seen...
should not ever use the old method `renderTemplate`, unless you put three arguments (lines 355 and 380 of "harta.js").

Use the new `applyTemplate` Is more comfortable and safer (as used in line 336).

> I think I found. I need to add these lines for each layer on my map: ... Is this true?

not necessarily, is used to correct another problem: duplicate fid 

> And maybe they have the same created fid ({tip} + {id}).

Yes, this sure is a problem. The solution is to use 

```
featureContext: {
   fid: function(feature) {
     return feature.fid;
   },
...
```

(since you do not use BBOX)

**Comment by jorix** [comment]
@bogdandragomir Tell me if it has been an open front in this issue. I'm not sure if I forgot to answer something.

**Comment by bogdandragomir** [comment]
1. you don't answer to this question yet (see screen shot above):
   _But it looks like you add some more spaces between these structures: ${.name}${eIndisponibila}._
2. if I use on layerLucrari (the layer with black lines between features, road segments with repairs) this code the popup does not show at all:

```
featureContext: {
   fid: function(feature) {
     return feature.fid;
   },
...
```

You can test here: http://test2.trafficguide.ro/ on the north-west of the map.
![snap181](https://f.cloud.github.com/assets/2846921/34723/83f0a454-513a-11e2-9eca-e6df895e768e.jpg)
This is the last problem without a solution on this thread.

Thank you!

**Comment by jorix** [comment]
> 1 ... But it looks like you add some more spaces between these structures: ${.name}${eIndisponibila}.

I've looked at the specific case and the camera name is: `Cluj Napoca - Piata Avram Iancu &nbsp;` so in this case is a data problem.

> 2 if I use on layerLucrari (the layer with black lines between features, road segments with repairs) this code the popup does not show at all:

Is a bug, try 413ca11c20c2f38f76089f58d247911897790874 (in this layer `fid` is numeric, and the argument `featureId` is string, so if we do not use a strict comparison, I think this will work)

(this regression is introduced by 3292db369fb238991eb917aba409df73c5eca182)

**Comment by bogdandragomir** [comment]
1. You are right, I would have to check other situations, I see now only this camera tooltip shows the space. 
   I am sorry you spent time for nothing.
2. Yes, it works fine. http://test2.trafficguide.ro/

I think you can close this issue and issue #9.

The only problem left is this, from Issue #7:
![snap183](https://f.cloud.github.com/assets/2846921/35384/b8e6aac4-51e3-11e2-8172-ce8ba13515b8.jpg)
I don't know what to do.

Thank you Jorix!

**Comment by jorix** [comment]
> I don't know what to do.

Sorry, sorry :-( I misspelled the solution (is not `return feature.fid;`) try: 

```
featureContext: {
   fid: function(feature) {
     return feature.id;
   },
```

(cut and paste, and then did not look at remove the "f", apologies)

**Comment by jorix** [comment]
...and then I thought that you had made ​​changes in CMS and you used a fid without duplicates ...what confusion I created!

I hope it works now ;-)

**Comment by bogdandragomir** [comment]
Thank you, everything is OK now. 
No need for apologies, it is just the test version and we're still on holiday :)

**Comment by jorix** [comment]
Right, so we can close on 8 and 9 and will leave open the 7 a few days (if there is still something to be adjusted)

For me it is interesting and satisfying contrast the theoretical architecture of the control with a complex real case like yours.

...and Happy New Year!

**Comment by bogdandragomir** [comment]
Jorix, your control is unique and very useful, there is no competitor from my research. 
I know that our application is an essential tool for a government agency in charge of roads in Romania.
So it is far away from just a theoretical architecture :)

Happy New Year and thanks again for all your help!
